/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTSCAN_H
#define FTSCAN_H

#ifdef __cplusplus

extern "C" {

#endif

/* function declarations */
typedef struct ref_state {
    int selected;
    int locked;
    int timediff;
} ref_state_t;


int fts_can_gnssA_poll(int *error);

int fts_can_gnss_get_ref_state(struct ref_state *gps_state, struct ref_state *bd_state);

#ifdef __cplusplus

  }

#endif /* end of __cplusplus */
#endif /* FTSCAN_H */
