
#ifndef FTSSETDO_H
#define FTSSETDO_H



/* function declarations */
void init_ftsSetDo(void);
void ftsSetCmdThread();

#define FTS_FRAME_CLK_ID 0x70


#define FTS_SET_CMD_TYPE_SCALAR 1
#define FTS_SET_CMD_TYPE_TABLE 2



#define FTS_SET_CMD_SCALAR_CLK_STATE 1
#define FTS_SET_CMD_SCALAR_CLK_MODE 2


#define FTS_SET_SCALAR_FRAME_CLK_STATE 1
#define FTS_SET_SCALAR_FRAME_CLK_MODE 2


#define FTS_SET_CMD_TABLE_REF 1
#define FTS_SET_CMD_TABLE_NTP 2

//new define 
#define FTS_CAN_FRAME_CMD_CODE_PTP_SET_MODE 0x01
#define FTS_CAN_FRAME_CMD_CODE_PTP_POLL 0x02
#define FTS_CAN_FRAME_CMD_CODE_PTP_POLL_REPLY 0x02
#define FTS_CAN_FRAME_CMD_CODE_PTP_GET_STATE 0x02
#define FTS_CAN_FRAME_CMD_CODE_PTP_GET_STATE_REPLY 0x02
#define FTS_CAN_FRAME_CMD_CODE_PTP_SET_PARAM 0x11

#define FTS_CAN_FRAME_PTP_SET_IP_P1 0 
#define FTS_CAN_FRAME_PTP_SET_IP_P2 1  
#define FTS_CAN_FRAME_CMD_CODE_PTP_SET_IP_P1 0
#define FTS_CAN_FRAME_CMD_CODE_PTP_SET_IP_P2 1

#define FTS_CAN_CMD_CODE_PTP_POLL 0x02

#define FTS_CAN_CODE_GNSSA_POLL 0x02
#define FTS_CAN_CODE_POLL 0x02
#define FTS_CAN_CODE_GNSSB_POLL 0x03
#define FTS_CAN_CODE_GNSSA_GET_STATE 0x04
#define FTS_CAN_CODE_PWRA0_GET 0x05
#define FTS_CAN_CODE_PWRA1_GET 0x06
#define FTS_CAN_CODE_PWRB0_GET 0x07
#define FTS_CAN_CODE_PWRB1_GET 0x08

#define FTS_CAN_CODE_BOARD_OK 0x0
#define FTS_CAN_CODE_BOARD_ERROR 0x1
#define FTS_CAN_CODE_BOARD_NO_RESPONSE 0x0
#define FTS_CAN_CODE_BOARD_OK_RESPONSE 0x1

#define FTS_GPS_SELECTED 0
#define FTS_GPS_UNSELECTED 1
#define FTS_BD_SELECTED 0
#define FTS_BD_UNSELECTED 1
#define FTS_GPS_LOCK 0
#define FTS_GPS_UNLOCK 1
#define FTS_BD_LOCK 0
#define FTS_BD_UNLOCK 1








       
#endif /* FTSSETDO_H */
