/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTSCLKTRAP_H
#define FTSCLKTRAP_H

/* function declarations */
void send_ftsClkTrap_trap(unsigned int clientreg,  void *clientarg);

void init_ftsClkTrap(void);


#endif /* FTSCLKTRAP_H */
