/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTSCAN_H
#define FTSCAN_H

#include "can.h"


#define FTS_BOARD_TYPE_NTP 0
#define FTS_BOARD_TYPE_PTP 1
#define FTS_BOARD_TYPE_10M 2
#define FTS_BOARD_TYPE_1PPS 3
#define FTS_BOARD_TYPE_IRIG_B 4
#define FTS_BOARD_TYPE_NULL 5


/* function declarations */
unsigned int fts_can_mk_send_id(unsigned int slot, unsigned int board_type);
void send_ftsClkTrap_trap(unsigned int clientreg,  void *clientarg);
int fts_can_send_and_recv(struct can_frame *send_frame, struct can_frame *recv_frame);
void init_ftsCan(void);


#endif /* FTSCAN_H */
