/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef FTSPTPTABLE_H
#define FTSPTPTABLE_H

/* function declarations */
void init_ftsPtpTable(void);
void initialize_table_ftsPtpTable(void);
Netsnmp_Node_Handler ftsPtpTable_handler;

/* column number definitions for table ftsPtpTable */
#define COLUMN_FTSPTPSLOT		1
#define COLUMN_FTSPTPERROR		 2
#define COLUMN_FTSPTPMODE		 3
#define COLUMN_FTSPTPSYNRATE		4
#define COLUMN_FTSPTPDELAYRATE		5


#endif /* FTSPTPTABLE_H */
